apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicex
spec:
  selector:
    matchLabels:
      app: servicex
  template:
    metadata:
      labels:
        app: servicex
        version: "200"
    spec:
      containers:
      - name: servicex
        image: wesleywillians/circuit-breaker-example-go:latest
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicex-error
spec:
  selector:
    matchLabels:
      app: servicex
  template:
    metadata:
      labels:
        app: servicex
        version: "504"
    spec:
      containers:
      - name: servicex
        image: wesleywillians/circuit-breaker-example-go:error-504
        ports:
        - containerPort: 8000
        env:
          - name: error
            value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: servicex-service
spec:
  type: ClusterIP
  selector:
    app: servicex 
  ports:
  - port: 80
    targetPort: 8000
